# Auto Update Configuration
# This file configures automated update behavior for the repository

update_settings:
  # Dependency update frequency
  dependency_updates:
    frequency: "weekly"  # daily, weekly, monthly
    day: "monday"
    time: "09:00"
    
  # Security update behavior
  security_updates:
    auto_merge_minor: true
    auto_merge_patch: true
    auto_merge_major: false
    notify_on_critical: true
    
  # Version bumping strategy
  version_strategy:
    auto_bump_patch: true  # For patch updates
    auto_bump_minor: false # For minor updates (requires review)
    auto_bump_major: false # For major updates (requires review)
    
  # Testing requirements
  testing:
    run_tests_before_merge: true
    require_all_checks_pass: true
    run_security_scan: true
    
  # Notification settings
  notifications:
    slack_webhook: ""  # Add your Slack webhook URL
    discord_webhook: ""  # Add your Discord webhook URL
    email_notifications: false
    
  # Deployment settings
  deployment:
    auto_deploy_staging: true
    auto_deploy_production: false
    require_approval_production: true
    
  # Code quality
  code_quality:
    enforce_linting: true
    enforce_formatting: true
    require_code_review: true
    min_reviewers: 1