version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@me"
    assignees:
      - "@me"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    # Allow both direct and indirect updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Group updates by dependency name
    groups:
      express:
        patterns:
          - "express*"
      security:
        patterns:
          - "*"
        update-types:
          - "security"
    # Ignore specific dependencies if needed
    ignore:
      - dependency-name: "sqlite3"
        update-types: ["version-update:semver-major"]