export { default as TeacherLoginRegister } from './teacher/LoginRegister'
export { default as TeacherDashboardScreen } from './teacher/Dashboard'
export { default as TeacherProfileScreen } from './teacher/Profile'
export { default as TeacherJobSearch } from './teacher/JobSearch'
export { default as TeacherJobDetail } from './teacher/JobDetail'
export { default as TeacherApplicationsScreen } from './teacher/Applications'
export { default as TeacherMessages } from './teacher/Messages'
export { default as TeacherInterviewsScreen } from './teacher/Interviews'
export { default as TeacherNotifications } from './teacher/Notifications'
export { default as TeacherSettingsScreen } from './teacher/Settings'

export { default as InstitutionLoginRegister } from './institution/LoginRegister'
export { default as InstitutionDashboardScreen } from './institution/Dashboard'
export { default as InstitutionProfileScreen } from './institution/Profile'
export { default as InstitutionPostJob } from './institution/PostJob'
export { default as InstitutionJobsManagement } from './institution/JobsManagement'
export { default as InstitutionApplications } from './institution/Applications'
