name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Check if PR is from Dependabot
      if: github.actor == 'dependabot[bot]'
      run: echo "Dependabot PR detected"
      
    - name: Wait for status checks
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        check-name: 'test'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
        allowed-conclusions: success,skipped
        
    - name: Enable auto-merge
      if: github.actor == 'dependabot[bot]'
      run: |
        gh pr merge --auto --merge "${{ github.event.pull_request.number }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}