name: Dependabot auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  checks: read
  statuses: read

jobs:
  auto-approve-and-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Approve Dependabot PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for non-major
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            const title = pr.data.title || '';
            const isMajor = /\bmajor\b/i.test(title) || /\bchore\(deps\): update.*to v?\d+\.0\.0/.test(title);
            if (isMajor) {
              core.info('Skipping auto-merge for major updates.');
              return;
            }
            await github.graphql(`
              mutation($pull: ID!) {
                enablePullRequestAutoMerge(input: { pullRequestId: $pull, mergeMethod: SQUASH }) {
                  clientMutationId
                }
              }
            `, { pull: pr.data.node_id });
            core.info('Auto-merge enabled for this PR.');
